php-crontab:
  environment:
    WWW_DATA_FOLDER: /data/www/public_html
    CRONTAB_STOCK_UPDATE: "*/5 * * * * php /data/www/public_html/shell/stockupdate.php --profile
            firstkid"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: webserver=1
  tty: true
  image: bogdancostea/php-crontab
  links:
  - elasticsearch:elasticsearch
  - database:database
  volumes:
  - "${php_storage}:/data/www"
  stdin_open: true
webserver:
  environment:
    WWW_DATA_FOLDER: /data/www/public_html
    WWW_CHECKOUT_FOLDER: /data/www
    GIT_AUTO_CHECKOUT: "${git_autocheckout}"
    GIT_BRANCH: "${git_branch}"
    GIT_REMOTE: "${git_remote}"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: webserver=1
  tty: true
  image: bogdancostea/webserver
  links:
    - elasticsearch:elasticsearch
    - database:database
  volumes:
  - "${php_storage}:/data/www"
  stdin_open: true
elasticsearch:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: webserver=1
  tty: true
  image: elasticsearch
  stdin_open: true

pxc-clustercheck:
  image: flowman/percona-xtradb-cluster-clustercheck:v2.0
  net: "container:database"
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
      - 'pxc-data'
pxc-server:
  image: flowman/percona-xtradb-cluster:5.6.28-1
  net: "container:database"
  environment:
    MYSQL_ROOT_PASSWORD: "${mysql_root_password}"
    PXC_SST_PASSWORD: "${pxc_sst_password}"
    MYSQL_DATABASE: "${mysql_database}"
    MYSQL_USER: "${mysql_user}"
    MYSQL_PASSWORD: "${mysql_password}"
  labels:
    io.rancher.container.hostname_override: container_name
  volumes_from:
      - 'pxc-data'
  entrypoint: bash -x /opt/rancher/start_pxc
pxc-data:
  image: flowman/percona-xtradb-cluster:5.6.28-1
  net: none
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  volumes:
    - /var/lib/mysql
    - /etc/mysql/conf.d
    - /docker-entrypoint-initdb.d
  command: /bin/true
  labels:
    io.rancher.container.start_once: true
database:
  image: flowman/percona-xtradb-cluster-confd:v0.2.0
  labels:
    io.rancher.sidekicks: pxc-clustercheck,pxc-server,pxc-data
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label: webserver=1
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  volumes_from:
      - 'pxc-data'